FROM debian:buster
RUN apt-get update -y \
    && apt-get install -y mariadb-server
COPY mariadb_install.sh /home/
RUN mysql_install_db --user=mysql
ENTRYPOINT ["/home/mariadb_install.sh"]
CMD ["mysqld_safe"]