FROM alpine:3.16.2
COPY html_directory /usr/share/nginx/html
COPY Certificates/localhost.crt /etc/ssl/certs
COPY Certificates/localhost.key /etc/ssl/private
RUN apk update && apk add \
    nginx
COPY default.conf /etc/nginx/http.d
CMD ["nginx", "-g", "daemon off;"]