FROM debian:buster
RUN apt-get update -y && \
    apt-get install -y \
    php-fpm \
    php-mysql \
    curl \
    mariadb-client \
    netcat
RUN mkdir /run/php/ && chmod 755 /run/php/
RUN mkdir -p /var/www/html/daalmeid.42.fr \
    && cd /var/www/html/daalmeid.42.fr \
    && curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp \
    && curl -OL https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php \
    && wp --allow-root core download
RUN sed -i 's:listen = /run/php/php7.3-fpm.sock:listen = 9000:g' /etc/php/7.3/fpm/pool.d/www.conf
COPY wp_install.sh /var/www/html/
ENTRYPOINT ["/var/www/html/wp_install.sh"]
CMD ["php-fpm7.3", "-F", "-R"]